name: "Docker Image Build"

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_images:
    name: Build Runner Images    
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
    
      - name: "Build Image"
        run: docker buildx build --platform linux/amd64,linux/arm64 images/ubuntu-jammy/  

