name: Runner Lambda
on:
  push:
    branches:
      - develop
  pull_request:
    paths:
      - .github/workflows/runner-build.yml
      -  "lambda/runner/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    container:
      image: node:${{ matrix.node }}
    defaults:
      run:
        working-directory: lambda/runner/

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        run: npm run prettier

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test:ci
    
      - name: Build lambda
        run: npm run build

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Runner Tests
          path: lambda/runner/test_reports/jest-*.xml
          reporter: jest-junit
     
      - name: Upload Test Coverage
        uses: codecov/codecov-action@v3
        with:
          name: runner
          working-directory: lambda/runner/coverage/
          files: ./cobertura-coverage.xml
          flags: unittests
          fail_ci_if_error: true